# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0002_auto_20170716_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicional',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
