# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0006_auto_20170718_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='acai',
            name='tamanho',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
