# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0011_remove_casadinho_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='acaienergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tamanho', models.CharField(max_length=1)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
