# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0014_acaicreme_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaienergy',
            name='img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
