# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0017_fondue_milkshake_petit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petit',
            name='tamanho',
        ),
    ]
