# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 25, 18, 13, 38, 614008)),
        ),
        migrations.AddField(
            model_name='caixa',
            name='tipo',
            field=models.CharField(default='Entrada', max_length=10),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
