# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs', models.CharField(max_length=200)),
                ('adicionais', models.ManyToManyField(to='outros.adicional')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.produto')),
            ],
        ),
        migrations.AddField(
            model_name='comanda',
            name='itens',
            field=models.ManyToManyField(to='pedidos.item'),
        ),
    ]
