# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20170716_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Medio'), ('G', 'Grande')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
