# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-17 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_item_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
