# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0007_acai_tamanho'),
        ('pedidos', '0005_auto_20170716_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='comanda_acai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default='0', max_digits=5)),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.acai')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande')], max_length=1),
        ),
    ]
