# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0007_acai_tamanho'),
        ('pedidos', '0006_auto_20170718_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda_acai',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='comanda',
            name='itens',
        ),
        migrations.AddField(
            model_name='comanda',
            name='itens',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='outros.produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comanda_acai',
            name='itens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.produto'),
        ),
        migrations.AlterField(
            model_name='comanda_acai',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
