# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0017_fondue_milkshake_petit'),
        ('pedidos', '0013_comanda_acaicreme'),
    ]

    operations = [
        migrations.CreateModel(
            name='comanda_fondue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande')], max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.fondue')),
            ],
        ),
        migrations.CreateModel(
            name='comanda_milkshake',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande')], max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.milkshake')),
            ],
        ),
        migrations.CreateModel(
            name='comanda_petit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tamanho', models.CharField(choices=[('P', 'Pequeno'), ('G', 'Grande')], max_length=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.petit')),
            ],
        ),
    ]
