# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0014_comanda_fondue_comanda_milkshake_comanda_petit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda_petit',
            name='tamanho',
        ),
    ]
