# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_remove_comanda_petit_tamanho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda_fondue',
            name='tamanho',
        ),
    ]
