# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0020_sorvete'),
        ('pedidos', '0016_remove_comanda_fondue_tamanho'),
    ]

    operations = [
        migrations.CreateModel(
            name='comanda_sorvete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('itens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.acai')),
            ],
        ),
    ]
