# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_comanda_sorvete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda_sorvete',
            name='itens',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.sorvete'),
        ),
    ]
